export {MainBannerSvg} from './MainBannerSvg'
export {DeathSvg} from './DeathSvg'
export { HandSkull } from './HandSkull'
export { Heart } from './Heart'
export { WorldSecond } from './WorldSecond'
export { WaterSvg } from './WaterSvg'
export {LordsOfWaterStraight} from './LordsOfWaterStraight'
export {Clock} from './Clock'
export { Instagram } from './Instagram'
import { Arrow } from './Arrow'
