export {Navbar} from './Navbar/Navbar'
export { MainBanner } from './MainBanner/MainBanner'
export {Marque} from './Marque/Marque'
export {SecondMarque} from './SecondMarque/SecondMarque'
export {VideoSection} from './VideoSection/VideoSection'
export {SmallBanner} from './SmallBanner/SmallBanner'
export { Map } from './Map/Map'
export {Footer} from './Footer/Footer'
